import os

SECRET_KEY = 'ENTER_SECRET_KEY'
DEBUG = True

os.environ["YELP_CONSUMER_KEY"] = "ENTER_YELP_CONSUMER_KEY"
os.environ["YELP_CONSUMER_SECRET"] = "ENTER_YELP_CONSUMER_SECRET"
os.environ["YELP_TOKEN"] = "ENTER_YELP_TOKEN"
os.environ["YELP_TOKEN_SECRET"] = "ENTER_YELP_TOKEN_SECRET"
os.environ["SECRET_KEY"] = "ENTER_SECRET_KEY"
os.environ["GOOGLE_MAPS_KEY"] = "ENTER_GOOGLE_MAPS_KEY"